<?php
// Sample Nextcloud config.php for this Termux setup.
// Copy to ~/nextcloud/config/config.php and replace every <PLACEHOLDER>.
// instanceid, passwordsalt, and secret are auto-generated by the Nextcloud
// installer -- never reuse the values from any other install.
$CONFIG = array (
  'instanceid' => '<AUTO_GENERATED_BY_INSTALLER>',
  'passwordsalt' => '<AUTO_GENERATED_BY_INSTALLER>',
  'secret' => '<AUTO_GENERATED_BY_INSTALLER>',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '127.0.0.1',
    2 => '<YOUR_LAN_IP>',
    3 => '<YOUR_PUBLIC_DOMAIN>',
  ),
  'datadirectory' => '/data/data/com.termux/files/home/nextcloud-data',
  'dbtype' => 'mysql',
  'overwrite.cli.url' => 'http://localhost',
  'dbname' => 'nextcloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'ncadmin',
  'dbpassword' => '<YOUR_DB_PASSWORD>',
  'installed' => true,
  'overwriteprotocol' => 'https',
  'default_phone_region' => 'US',
);
